<?php
namespace EA\Controller;

use Base\Controller\BaseFunctions;
use Base\Controller\CrudController;

class EAPriceController extends CrudController{
    public function __construct() {
        $this->title        = "Preços";
        $this->table        = 'EAPrice';
        $this->entity       = 'EA\Entity\\'.$this->table ;
        $this->service      = 'EA\Service\\'.$this->table ;
        $this->form         = 'EA\Form\\'.$this->table ;
        $this->controller   = "ea-price";
        $this->route        = 'ea-price/defaults';

        $this->_listView = array(
            'title' => $this->title,
            'icon' => 'fa-file-text',
            'route' => $this->route,
            'controller' => $this->controller,
            'actions' => array(
                'enable' =>true,
                'defaults' => array(
                    'edit' => array(
                        'enable' => true,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-edit'
                    ),
                    'delete' => array(
                        'enable' => true,
                        'class' => 'btn btn-danger decision',
                        'icon' => 'fa fa-trash'
                    ),
                    'view' => array(
                        'enable' => false,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-eye'
                    ),
                ),
            ),
            'fields' => array(
                'id'=>array(
                    'label' => 'Id',
                    'list' => true,
                ),
                'firstStr'=>array(
                    'label' => 'Primeira parcela?',
                    'list' => true,
                ),
                'title'=>array(
                    'label' => 'Título',
                    'list' => true,
                ),
                'price'=>array(
                    'label' => 'Preço',
                    'list' => true,
                ),
                'eaStr'=>array(
                    'label' => 'Expert Advisor',
                    'list' => true,
                ),
                'freeStr'=>array(
                    'label' => 'Grátis',
                    'list' => true,
                ),
            ),
        );
    }

    public function indexAction($entity = null, $per_page = 10)
    {
        return parent::indexAction($entity, $per_page); // TODO: Change the autogenerated stub
    }
}
