<?php
use Admin\Entity\User;
global $user;

$user = $this->userIdentity('Admin');
$user = $this->getEm()->getRepository('Admin\Entity\User')->findOneById($user);

$db_layouts = $this->getEm()->getRepository('Configuration\Entity\Layout')->findAll();

$layout_class = '';
if(!empty($db_layouts))
{
    foreach($db_layouts as $db_layout){
        if($db_layout->getActive()){
            $layout_class = $db_layout->getClass();
        }
    }
}



if($user && $user instanceof User) {
?>
<!DOCTYPE html>
<html lang="pt-BR" class="<?=$layout_class?>">
    <head>
        <meta charset="utf-8">
        <!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

        <base href="<?php echo $this->basePath(); ?>" />

        <title>Bot Champions</title>
        <meta name="description" content="">
        <meta name="author" content="">

        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">


        <link rel="stylesheet" type="text/css" media="screen" href="/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-production-plugins.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-production.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-skins.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-rtl.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/demo.min.css">
        <link rel="shortcut icon" href="/img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/img/favicon/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">
        <link rel="apple-touch-icon" href="/img/splash/sptouch-icon-iphone.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/img/splash/touch-icon-ipad.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/img/splash/touch-icon-iphone-retina.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/img/splash/touch-icon-ipad-retina.png">
        <link rel="stylesheet" type="text/css" media="screen" href="/css/styles.css">


        <?php
        if (isset($_SESSION['Admin']))
            $session = (array)$_SESSION['Admin'];

        if (isset($_SESSION['Permissions']))
            $sessionP = (array)$_SESSION['Permissions'];

        if (isset($sessionP))
            foreach ($sessionP as $v) {
                if (isset($v['storage']))
                $informations = $v['storage'];
            }

        if (isset($sessionC))
            foreach ($sessionC as $v) {
                if (isset($v['storage']))
                    $cursos = $v['storage'];
            }

        if (isset($sessionE))
            foreach ($sessionE as $k => $v) {
                if (isset($v['storage']))
                    $expiracoes = $v['storage'];
            }

        if ($user instanceof User) {
            $foto = ($user->getImagem() != '' && file_exists('public/img/clientes/' . $user->getImagem())) ? '/img/clientes/' . $user->getImagem() : '/img/clientes/sem_imagem.jpg';
        }

        ?>

    </head>

    <script data-pace-options='{ "restartOnRequestAfter": true }' src="/adminitrative/js/plugin/pace/pace.min.js"></script>
    <script src="/js/jquery-3-2-1.min.js"></script>

    <script>
        if (!window.jQuery) {
            document.write('<script src="/admin/js/libs/jquery-3.2.1.min.js"><\/script>');
        }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script>
        if (!window.jQuery.ui) {
            document.write('<script src="/admin/js/libs/jquery-ui.min.js"><\/script>');
        }
    </script>
    <script type="text/javascript" src="/js/angular.js"></script>
    <script type="text/javascript" src="/js/main.js"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/jquery.maskMoney.js"></script>
    <script type="text/javascript" src="/js/jquery.inputmask.js"></script>
    <script type="text/javascript" src="/js/jquery.inputmask.date.extensions.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script>

        function verifyAccountCpf(event,href) {
            event.preventDefault();
            console.log(href);
            var temConta = 0;
            var userId = '<?=$user->getId()?>';
            var contaId = null;

            $.ajax({
                url: '/api/user-conta',
                type: "GET",
                async: false,
                data: {
                    'filter': [
                        {
                            'field': 'user',
                            'where': 'AND',
                            'type': 'eq',
                            'value': userId
                        }
                    ]
                },
                success: function (o) {
                    var contas = o._embedded.user_conta;

                    if(contas.length == 0){
                        despatchCreateAccount();
                    }

                    for(index in contas) {
                        var conta = contas[index];
                        if((conta.cpf != null && conta.cpf != '') || (conta.cnpj != null && conta.cnpj != '')){
                            location.href = href;
                        }else{
                            despatchCreateAccount();
                        }
                    }
                }
            });
        }
    </script>

<body class="desktop-detected pace-done animated fadeIn <?=$layout_class?>">
    <header id="header">
        <div id="logo-group">
            <span align="center" id="logo">
                <a href="<?=$this->url('admin');?>">
                    <img src="/img/logo/logo_branco.png">
                </a>
            </span>
        </div>
        <div class="pull-right">
            <div id="hide-menu" class="btn-header pull-right">
                <span>
                    <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu">
                        <i class="fa fa-reorder"></i>
                    </a>
                </span>
            </div>
            <div id="logout" class="btn-header transparent pull-right">
                <span>
                    <a href="/auth/logout" title="Sign Out" data-action="userLogout" data-logout-msg="Para a sua própria segurança depois de deslogar feche essa aba no navegador">
                        <i class="fa fa-sign-out"></i>
                    </a>
                </span>
            </div>
            <div id="fullscreen" class="btn-header transparent pull-right">
                <span>
                    <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen">
                        <i class="fa fa-arrows-alt"></i>
                    </a>
                </span>
            </div>
        </div>
    </header>
    <aside id="left-panel">
        <div class="login-info">
            <span>
                <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
                    <img src="<?=$foto?>" alt="me" class="online">
                    <span>
                        <?=$user->getNome();?>
                    </span>
                    <i class="fa fa-angle-down"></i>
                </a>
            </span>
        </div>
        <nav>
            <ul>
                <?php
                $menu = $this->getMenu($user);
                if(!empty($menu))
                {
                    $count_avos = 0;
                    foreach($menu as $k => $item){
                        if(isset($item['dropdown'])){
                            ?>
                            <li id="menu-avo-<?=$count_avos?>"  class="menu-avo">
                                <a href="#" <?=($item['target'])?'target="'.$item['target'].'"':'';?> title="<?=$item['title']?>">
                                    <i class="fa fa-lg fa-fw <?=$item['icon']?>"></i>
                                    <span class="menu-item-parent"><?=$item['title']?></span>
                                </a>
                                <ul >
                                    <?php
                                    $dropdown = $item['dropdown'];
                                    if(!empty($dropdown))
                                    {
                                        $count_pais = 0;
                                        foreach($dropdown as $i => $subitem)
                                        {
                                            if(isset($subitem['course']) && $subitem['course'] && $subitem['course']){
                                                $ativo = $expiracoes[$subitem['course_id']];
                                            }

                                            $recurso = $subitem['resource'];
                                            $item = $i;
                                            $acao = $subitem['action'];

                                            $hasPermission = $user->hasPermission($recurso, $item, $acao, $informations);

                                            if (($hasPermission || $user->getIsAdmin()) || isset($subitem['course']) || $subitem['authorize']) {

                                                ?>
                                                <li id="menu-pai-<?=$count_avos?>-<?=$count_pais?>"  class="menu-pai">
                                                    <a <?= (isset($subitem['route'])) ? 'href="' . $subitem['route'] . '""' : ''; ?>>
                                                    <span class="menu-item-parent">
                                                        <?= $subitem['title'] ?>
                                                        <?php
                                                        if ((isset($subitem['course']) && $subitem['course']) && (isset($subitem['free']) && !$subitem['free']) && !$ativo) {
                                                            ?>
                                                            <small class="label-menu label pull-right bg-red bg-color-red padding-5">Pagar</small>
                                                            <?php
                                                        }

                                                        if (isset($subitem['free']) && $subitem['free']) {
                                                            ?>
                                                            <small class="label-menu label pull-right bg-green bg-color-green padding-5">Grátis</small>
                                                            <?php
                                                        }
                                                        ?>
                                                    </span>
                                                    </a>
                                                    <?php
                                                    if (isset($subitem['dropdown'])) {
                                                        if (!empty($subitem['dropdown'])) {
                                                            $count_filhos = 0;
                                                            ?>
                                                            <ul>
                                                                <?php
                                                                foreach ($subitem['dropdown'] as $j => $childitem) {
                                                                    $recurso = $childitem['resource'];
                                                                    $item = $j;
                                                                    $acao = $childitem['action'];
                                                                    $hasPermission = $user->hasPermission($recurso, $item, $acao, $informations);

                                                                    if (($hasPermission || $user->getIsAdmin()) || $childitem['authorize']) {
                                                                        ?>
                                                                        <li id="menu-filho-<?=$count_avos?>-<?=$count_pais?>-<?=$count_filhos?>" class="menu-filho">
                                                                            <a href="<?= $childitem['route'] ?>">
                                                                                <?= $childitem['title'] ?>
                                                                            </a>
                                                                        </li>
                                                                        <?php
                                                                        $count_filhos++;
                                                                    }
                                                                }
                                                                ?>
                                                            </ul>
                                                            <?php
                                                            if($count_filhos == 0){
                                                                ?>
                                                                <style>
                                                                    #menu-pai-<?=$count_avos?>-<?=$count_pais?>{
                                                                        display: none;
                                                                    }
                                                                </style>
                                                                <?php
                                                            }

                                                        }
                                                    }
                                                    ?>

                                                </li>
                                                <?php
                                                $count_pais++;
                                            }

                                        }
                                    }
                                    ?>
                                </ul>
                                <?php
                                if($count_pais == 0){
                                    ?>
                                    <style>
                                        #menu-avo-<?=$count_avos?>{
                                            display: none;
                                        }
                                    </style>
                                    <?php
                                }
                                ?>
                            </li>
                            <?php

                        }else{
                            $onclick = '';
                            if($item['title'] == 'Depósito/Resgate XM')
                            {
                                $onclick = 'verifyAccountCpf(event,this.href);';
                            }
                            ?>
                            <li class="">
                                <a <?=($onclick != '')?'onclick="'.$onclick.'"':'';?> <?=($item['target'])?'target="'.$item['target'].'"':'';?> href="<?=$item['route']?>">
                                    <i class="fa fa-lg fa-fw <?=$item['icon']?>"></i>
                                    <span class="menu-item-parent"><?=$item['title']?></span>
                                </a>
                            </li>
                            <?php
                        }
                        $count_avos++;
                    }
                }
                ?>
            </ul>
        </nav>
        <span class="minifyme" data-action="minifyMenu">
            <i class="fa fa-arrow-circle-left hit"></i>
        </span>
    </aside>
    <div id="main" role="main">
        <?php
        //$this->getMenu($user);
        echo $this->content;
        ?>
    </div>
    <div class="page-footer">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <span class="txt-color-white">© Bot Champions <?php echo date('Y') ?>.</span>
            </div>
            <div class="col-xs-12 col-sm-6">
                <span class="txt-color-white pull-right">Todos os Direitos Reservados.</span>
            </div>
        </div>
    </div>


    <script src="/js/app.config.js"></script>
    <script src="/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>
    <script src="/js/bootstrap/bootstrap.min.js"></script>
    <script src="/js/notification/SmartNotification.min.js"></script>
    <script src="/js/smartwidgets/jarvis.widget.min.js"></script>
    <script src="/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
    <script src="/js/plugin/sparkline/jquery.sparkline.min.js"></script>
    <script src="/js/plugin/jquery-validate/jquery.validate.min.js"></script>
    <script src="/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
    <script src="/js/plugin/select2/select2.min.js"></script>
    <script src="/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
    <script src="/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>
    <script src="/js/plugin/fastclick/fastclick.min.js"></script>
    <script src="/js/demo.min.js"></script>
    <script src="/js/app.min.js"></script>
    <script src="/js/speech/voicecommand.min.js"></script>
    <script src="/js/smart-chat-ui/smart.chat.ui.min.js"></script>
    <script src="/js/smart-chat-ui/smart.chat.manager.min.js"></script>
    <script src="/js/plugin/flot/jquery.flot.cust.min.js"></script>
    <script src="/js/plugin/flot/jquery.flot.resize.min.js"></script>
    <script src="/js/plugin/flot/jquery.flot.time.min.js"></script>
    <script src="/js/plugin/flot/jquery.flot.tooltip.min.js"></script>
    <script src="/js/plugin/moment/moment.min.js"></script>
    <script src="/js/plugin/fullcalendar/fullcalendar.min.js"></script>
    <script src="/js/plugin/vectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/js/plugin/vectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="/js/bootbox.js"></script>
    <script src="/js/geral.js"></script>

    <script src="/js/plugin/datatables/jquery.dataTables.min.js"></script>
    <script src="/js/plugin/datatables/dataTables.colVis.min.js"></script>
    <script src="/js/plugin/datatables/dataTables.tableTools.min.js"></script>
    <script src="/js/plugin/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/js/plugin/datatable-responsive/datatables.responsive.min.js"></script>


<!--[if IE 8]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->

<?php
if(!$user->getIsAdmin()){
    ?>
    <style>
        .demo.activate{
            display: none;
        }


        .demo{
            display: none;
        }
    </style>
    <?php
}
?>
<script>
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires="+d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for(var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    function checkCookie() {
        var user = getCookie("username");
        if (user != "") {
            alert("Welcome again " + user);
        } else {
            user = prompt("Please enter your name:", "");
            if (user != "" && user != null) {
                setCookie("username", user, 365);
            }
        }
    }

    function saveLayoutOption(element,active){
        $.ajax({
            url: "/api/layout-option",
            type: "GET",
            async: true,
            data: {
                'filter': [
                    {
                        'field' : 'element',
                        'type' : 'eq',
                        'value' : element
                    }
                ]
            },
            success: function(data) {
                var layout_option = data._embedded.layout_option[0];

                if(layout_option){
                    layout_option.active = active;

                    delete layout_option.createdAt;
                    delete layout_option.updatedAt;
                    delete layout_option._links;

                    data = JSON.stringify(layout_option);

                    $.ajax({
                        url: "/api/layout-option/" + layout_option.id,
                        type: "PUT",
                        async: true,
                        contentType : 'application/json',
                        data: data,
                        success: function(data) {
                            return true;
                        },
                        dataType: "json"
                    });
                }
            },
            dataType: "json"
        });
    }

    $.ajax({
        url: "/api/layout-option",
        type: "GET",
        success: function(data) {
            var layout_options = data._embedded.layout_option;
            for(i in layout_options){
                let layout_option = layout_options[i];
                if(layout_option.active == true){
                    if(layout_option.element != 'smart-topmenu'){
                        $("#" + layout_option.element).trigger('click');
                    }else{
                        $("#" + layout_option.element).attr('checked','checked');
                    }
                }
            }
        },
        dataType: "json"
    });

    $( ".demo input[type=checkbox]" ).click(function(){
        if (document.createEvent) {  // EVENTO DISPARANDO CLICANDO MANUAL
            $(".demo input[type=checkbox]").each(function () {
                if ($(this).is(':checked')) {
                    var element = this.id;
                    var result = saveLayoutOption(element, 1);
                } else {
                    var element = this.id;
                    var result = saveLayoutOption(element, 0);
                }
            });
        }else{ // EVENTO DISPARADO POR TRIGGER

        }
    });

    $(document).ready(function() {
        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        pageSetUp();

        $(".js-status-update a").click(function() {
            var selText = $(this).text();
            var $this = $(this);
            $this.parents('.btn-group').find('.dropdown-toggle').html(selText + ' <span class="caret"></span>');
            $this.parents('.dropdown-menu').find('li').removeClass('active');
            $this.parent().addClass('active');
        });

        $(function() {
            $("#sortable1, #sortable2").sortable({
                handle : '.handle',
                connectWith : ".todo",
                update : countTasks
            }).disableSelection();
        });

        $('.todo .checkbox > input[type="checkbox"]').click(function() {
            var $this = $(this).parent().parent().parent();

            if ($(this).prop('checked')) {
                $this.addClass("complete");
                $(this).parent().hide();

                $this.slideUp(500, function() {
                    $this.clone().prependTo("#sortable3").effect("highlight", {}, 800);
                    $this.remove();
                    countTasks();
                });
            } else {
                // insert undo code here...
            }

        })

        // count tasks
        function countTasks() {

            $('.todo-group-title').each(function() {
                var $this = $(this);
                $this.find(".num-of-tasks").text($this.next().find("li").size());
            });

        }

        var data = [], totalPoints = 200, $UpdatingChartColors = $("#updating-chart").css('color');

        function getRandomData() {
            if (data.length > 0)
                data = data.slice(1);

            // do a random walk
            while (data.length < totalPoints) {
                var prev = data.length > 0 ? data[data.length - 1] : 50;
                var y = prev + Math.random() * 10 - 5;
                if (y < 0)
                    y = 0;
                if (y > 100)
                    y = 100;
                data.push(y);
            }

            // zip the generated y values with the x values
            var res = [];
            for (var i = 0; i < data.length; ++i)
                res.push([i, data[i]])
            return res;
        }

        // setup control widget
        var updateInterval = 1500;
        $("#updating-chart").val(updateInterval).change(function() {

            var v = $(this).val();
            if (v && !isNaN(+v)) {
                updateInterval = +v;
                $(this).val("" + updateInterval);
            }

        });

        // setup plot
        var options = {
            yaxis : {
                min : 0,
                max : 100
            },
            xaxis : {
                min : 0,
                max : 100
            },
            colors : [$UpdatingChartColors],
            series : {
                lines : {
                    lineWidth : 1,
                    fill : true,
                    fillColor : {
                        colors : [{
                            opacity : 0.4
                        }, {
                            opacity : 0
                        }]
                    },
                    steps : false

                }
            }
        };

        var plot = $.plot($("#updating-chart"), [getRandomData()], options);

        /* live switch */
        $('input[type="checkbox"]#start_interval').click(function() {
            if ($(this).prop('checked')) {
                $on = true;
                updateInterval = 1500;
                update();
            } else {
                clearInterval(updateInterval);
                $on = false;
            }
        });

        function update() {
            if ($on == true) {
                plot.setData([getRandomData()]);
                plot.draw();
                setTimeout(update, updateInterval);

            } else {
                clearInterval(updateInterval)
            }

        }

        var $on = false;

        /*end updating chart*/

        /* TAB 2: Social Network  */

        $(function() {
            // jQuery Flot Chart
            var twitter = [[1, 27], [2, 34], [3, 51], [4, 48], [5, 55], [6, 65], [7, 61], [8, 70], [9, 65], [10, 75], [11, 57], [12, 59], [13, 62]], facebook = [[1, 25], [2, 31], [3, 45], [4, 37], [5, 38], [6, 40], [7, 47], [8, 55], [9, 43], [10, 50], [11, 47], [12, 39], [13, 47]], data = [{
                label : "Twitter",
                data : twitter,
                lines : {
                    show : true,
                    lineWidth : 1,
                    fill : true,
                    fillColor : {
                        colors : [{
                            opacity : 0.1
                        }, {
                            opacity : 0.13
                        }]
                    }
                },
                points : {
                    show : true
                }
            }, {
                label : "Facebook",
                data : facebook,
                lines : {
                    show : true,
                    lineWidth : 1,
                    fill : true,
                    fillColor : {
                        colors : [{
                            opacity : 0.1
                        }, {
                            opacity : 0.13
                        }]
                    }
                },
                points : {
                    show : true
                }
            }];

            var options = {
                grid : {
                    hoverable : true
                },
                colors : ["#568A89", "#3276B1"],
                tooltip : true,
                tooltipOpts : {
                    //content : "Value <b>$x</b> Value <span>$y</span>",
                    defaultTheme : false
                },
                xaxis : {
                    ticks : [[1, "JAN"], [2, "FEB"], [3, "MAR"], [4, "APR"], [5, "MAY"], [6, "JUN"], [7, "JUL"], [8, "AUG"], [9, "SEP"], [10, "OCT"], [11, "NOV"], [12, "DEC"], [13, "JAN+1"]]
                },
                yaxes : {

                }
            };

            var plot3 = $.plot($("#statsChart"), data, options);
        });

        // END TAB 2

        // TAB THREE GRAPH //
        /* TAB 3: Revenew  */

        $(function() {

            var trgt = [[1354586000000, 153], [1364587000000, 658], [1374588000000, 198], [1384589000000, 663], [1394590000000, 801], [1404591000000, 1080], [1414592000000, 353], [1424593000000, 749], [1434594000000, 523], [1444595000000, 258], [1454596000000, 688], [1464597000000, 364]], prft = [[1354586000000, 53], [1364587000000, 65], [1374588000000, 98], [1384589000000, 83], [1394590000000, 980], [1404591000000, 808], [1414592000000, 720], [1424593000000, 674], [1434594000000, 23], [1444595000000, 79], [1454596000000, 88], [1464597000000, 36]], sgnups = [[1354586000000, 647], [1364587000000, 435], [1374588000000, 784], [1384589000000, 346], [1394590000000, 487], [1404591000000, 463], [1414592000000, 479], [1424593000000, 236], [1434594000000, 843], [1444595000000, 657], [1454596000000, 241], [1464597000000, 341]], toggles = $("#rev-toggles"), target = $("#flotcontainer");

            var data = [{
                label : "Target Profit",
                data : trgt,
                bars : {
                    show : true,
                    align : "center",
                    barWidth : 30 * 30 * 60 * 1000 * 80
                }
            }, {
                label : "Actual Profit",
                data : prft,
                color : '#3276B1',
                lines : {
                    show : true,
                    lineWidth : 3
                },
                points : {
                    show : true
                }
            }, {
                label : "Actual Signups",
                data : sgnups,
                color : '#71843F',
                lines : {
                    show : true,
                    lineWidth : 1
                },
                points : {
                    show : true
                }
            }]

            var options = {
                grid : {
                    hoverable : true
                },
                tooltip : true,
                tooltipOpts : {
                    //content: '%x - %y',
                    //dateFormat: '%b %y',
                    defaultTheme : false
                },
                xaxis : {
                    mode : "time"
                },
                yaxes : {
                    tickFormatter : function(val, axis) {
                        return "$" + val;
                    },
                    max : 1200
                }

            };

            plot2 = null;

            function plotNow() {
                var d = [];
                toggles.find(':checkbox').each(function() {
                    if ($(this).is(':checked')) {
                        d.push(data[$(this).attr("name").substr(4, 1)]);
                    }
                });
                if (d.length > 0) {
                    if (plot2) {
                        plot2.setData(d);
                        plot2.draw();
                    } else {
                        plot2 = $.plot(target, d, options);
                    }
                }

            };

            toggles.find(':checkbox').on('change', function() {
                plotNow();
            });
            plotNow()

        });

        /*
         * VECTOR MAP
         */

        data_array = {
            "US" : 4977,
            "AU" : 4873,
            "IN" : 3671,
            "BR" : 2476,
            "TR" : 1476,
            "CN" : 146,
            "CA" : 134,
            "BD" : 100
        };

        $('#vector-map').vectorMap({
            map : 'world_mill_en',
            backgroundColor : '#fff',
            regionStyle : {
                initial : {
                    fill : '#c4c4c4'
                },
                hover : {
                    "fill-opacity" : 1
                }
            },
            series : {
                regions : [{
                    values : data_array,
                    scale : ['#85a8b6', '#4d7686'],
                    normalizeFunction : 'polynomial'
                }]
            },
            onRegionLabelShow : function(e, el, code) {
                if ( typeof data_array[code] == 'undefined') {
                    e.preventDefault();
                } else {
                    var countrylbl = data_array[code];
                    el.html(el.html() + ': ' + countrylbl + ' visits');
                }
            }
        });

        /* hide default buttons */
        $('.fc-toolbar .fc-right, .fc-toolbar .fc-center').hide();

        // calendar prev
        $('#calendar-buttons #btn-prev').click(function() {
            $('.fc-prev-button').click();
            return false;
        });

        // calendar next
        $('#calendar-buttons #btn-next').click(function() {
            $('.fc-next-button').click();
            return false;
        });

        // calendar today
        $('#calendar-buttons #btn-today').click(function() {
            $('.fc-button-today').click();
            return false;
        });

        // calendar month
        $('#mt').click(function() {
            $('#calendar').fullCalendar('changeView', 'month');
        });

        // calendar agenda week
        $('#ag').click(function() {
            $('#calendar').fullCalendar('changeView', 'agendaWeek');
        });

        // calendar agenda day
        $('#td').click(function() {
            $('#calendar').fullCalendar('changeView', 'agendaDay');
        });

        /*
         * CHAT
         */

        $.filter_input = $('#filter-chat-list');
        $.chat_users_container = $('#chat-container > .chat-list-body')
        $.chat_users = $('#chat-users')
        $.chat_list_btn = $('#chat-container > .chat-list-open-close');
        $.chat_body = $('#chat-body');

        /*
        * LIST FILTER (CHAT)
        */

        // custom css expression for a case-insensitive contains()
        jQuery.expr[':'].Contains = function(a, i, m) {
            return (a.textContent || a.innerText || "").toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
        };

        function listFilter(list) {// header is any element, list is an unordered list
            // create and add the filter form to the header

            $.filter_input.change(function() {
                var filter = $(this).val();
                if (filter) {
                    // this finds all links in a list that contain the input,
                    // and hide the ones not containing the input while showing the ones that do
                    $.chat_users.find("a:not(:Contains(" + filter + "))").parent().slideUp();
                    $.chat_users.find("a:Contains(" + filter + ")").parent().slideDown();
                } else {
                    $.chat_users.find("li").slideDown();
                }
                return false;
            }).keyup(function() {
                // fire the above change event after every letter
                $(this).change();

            });

        }

        // on dom ready
        listFilter($.chat_users);

        // open chat list
        $.chat_list_btn.click(function() {
            $(this).parent('#chat-container').toggleClass('open');
        })

        $.chat_body.animate({
            scrollTop : $.chat_body[0].scrollHeight
        }, 500);

    });

</script>

</body>
</html>
<?php
}else{
    header('Location: /auth');
    die;
}
?>
