<html>
	<head>
	</head>
	<body >
		<div style="width:100%;background-color: #444;" align="center">
			<p>&nbsp;</p>
    		<table   style="background-color: #fff" width="600">
    			<thead>
    				<tr>
        				<th>
        					<div style="width: 94%; padding: 3%; background-color:#132f3b;border-bottom: 3px solid #f87902;">
        						<h1 style="text-align:center;color:#fff;font-weight:bold"><?=$this->getConfiguracao('LOGO')?></h1>
        					</div>        					
        				</th>
    				</tr>
    			</thead>
    			<tbody >
    				<tr >
    					<td>
    						<div style="padding: 5px">
    							<h4>
    								<strong>Solicitação de Ativação</strong>
    							</h4>  
                                <p> 
                                	Houve uma solicitação de ativação do aporte enviada pelo <?=$this->nome?> através do sistema.
                                </p>
								<p>
									Acesse o aporte para análise do pedido clicando <a href="<?=$this->rota?>">aqui</a>
								</p>
                                <br/>
    						</div>    						
    					</td>
    				</tr>
    			</tbody>  
    			<tfoot>
    				<tr>
    					<td>
                            <div style="width: 94%; padding: 3%; background-color:#132f3b;border-top: 3px solid #f87902;color: #fff">
                                <h4>
                                    Informa&ccedil;&otilde;es para contato
                                </h4>
                                <strong>Tel: </strong> <?=$this->getConfiguracao('TELEFONEEMPRESA')?><br/>
                                <strong>Email: </strong> <?=$this->getConfiguracao('EMAILEMPRESA')?>
                            </div>
    					</td>
    				</tr>
    			</tfoot>  			
    		</table>
    		<p>&nbsp;</p>
		</div>
	</body>
</html>
