<?php
$form = $this->form;
$form->setAttribute('action', $this->url('sonuser-auth'));
$form->prepare();

?>
<div role="main" class="main">
    <section class="page-top">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-8">
        			<div class="row">
            			<div class="col-md-12">
            				<ul class="breadcrumb">
            					<li><a target="_parent" href="/auth">Home</a></li>
            					<li class="active">Login</li>
            				</ul>
            			</div>
            		</div>
            		<div class="row">
            			<div class="col-md-12">
            				<h1>Login</h1>
            			</div>
            		</div>
    			</div>
    			<div class="col-md-4">
    				<div style="margin-top:0px;" align="center">
    					<a style="font-size: 30px; font-family: 'Open Sans';font-weight: bold;color: #FFF;"
                           href="/auth">
                            <img style="max-height: 100px" class="img-responsive" src="/img/logo/logo_branco.png">
    					</a>
    				</div>
				</div>
    		</div>
    	</div>
    </section>
    <div class="container">
    	<div class="row">
            <div class="col-md-12 flashMessages">
                <?php 
                 $flash  =  $this->flashMessenger (); 
                 echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' )); 
                 echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' )); 
                 echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' )); 
                 echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));
                
                 ?>
            </div>
    	</div>
    </div>
    <br />
	<div class="container">

		<div class="row">
			<div class="col-md-12">

				<div class="row featured-boxes login">
					<div class="col-sm-6 col-sm-offset-3">
						<div class="featured-box featured-box-secundary default info-content">
							<div class="box-content">
							
								<?php 									
								if(isset($this->login) && is_object($this->login)){								
								?>
									<h4>
										<?php  
								        echo('Bem vindo <strong>'.$this->login->getNome().'</strong>');								         
								        ?>
									</h4>
									<h5>
										<?php echo('Acesse a área restrita ou faça o logout');?>
									</h5>
									<div class="row">
										<div class="col-md-4 col-md-offset-4">
											<div align="center">
												<a href="/admin">
    												<button class="btn-lg btn btn-success">
    													<i class="fa fa-lock"></i> Área Restrita
    												</button>
												</a>
											</div>
										</div>
									</div>
									<br />
									<div class="row">
										<div class="col-md-4 col-md-offset-4">
											<div align="center">
												<a href="/auth/logout">
    												<button class="btn-lg btn btn-warning">
    													<i class="fa fa-sign-out"></i> Logout
    												</button>
												</a>
											</div>
										</div>
									</div>
									
								<?php 
								}else{								    
    								?>
    								<h4>Já possuo uma conta</h4>
    								<?php if($this->error){?>
                                    	<p style="color: #E36159">Usuário ou senha inválidos</p>
                                    <?php }?>
    								<?php 
    								echo $this->form()->openTag($form);											
    								?>
    								
    									<div class="row">
    										<div class="form-group">
    											<div class="col-md-12">
    												<label>Usuário / E-mail</label>
    												<input name="email" type="text" value="" class="form-control input-lg" required>
    											</div>
    										</div>
    									</div>
    									<div class="row">
    										<div class="form-group">
    											<div class="col-md-12">
    												<a class="pull-right" href="/auth/lostpassword">(Perdeu a senha?)</a>
    												<label>Senha</label>
    												<input name="password" type="password" value="" class="form-control input-lg" required>
    											</div>
    										</div>
    									</div>
    									<div class="row">
    										<div class="col-md-12">
                                                <a href="/register" class="btn btn-success">
                                                    <i class="glyphicon glyphicon-plus"></i>&nbsp;Cadastrar
                                                </a>
                                                <button type="submit" class="btn btn-primary pull-right push-bottom" data-loading-text="Loading...">
                                                    <i class='glyphicon glyphicon-log-in'></i>&nbsp;&nbsp;Entrar
                                                </button>
    										</div>
    									</div>
    								
    								<?php 									
    								echo $this->form()->closeTag();
    								
								}
								?>
							</div>
						</div>
						<div style="display: none" class="display-none">
							<a href="http://www.merecomais.com" class="btn btn-lg btn-primary push-top">Ir para o site</a>							
						</div>
					</div>
					<div style="display: none" class="col-sm-6">
						<div class="featured-box featured-box-secundary default info-content">
							<div class="box-content">
								<h4>Registrar uma nova conta</h4>
								<form action="http://www.merecomais.com.br/register?internal=1" id="" method="post">
									<input type="hidden" name="rapidRegister" value="1">
									<div class="row">
										<div class="form-group">
											<div class="col-md-12">
												<label>Nome Completo</label>
												<input name="nome" type="text" value="" class="form-control input-lg" required>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="form-group">
											<div class="col-md-12">
												<label>E-mail</label>
												<input name="email" type="email" value="" class="form-control input-lg" required>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="form-group">
											<div class="col-md-6">
												<label>Senha</label>
												<input name="password" type="password" value="" class="form-control input-lg authPass" required>
											</div>
											<div class="col-md-6">
												<label>Repetir a Senha</label>
												<input name="confirmation" type="password" value="" class="form-control input-lg" required>
												<div style="display:none" class='alert alert-danger confirmation-alert' role='alert'>
                            					  <span class='glyphicon glyphicon-exclamation-sign' aria-hidden='true'></span>                        					
                            					  As senhas não conferem
                            					</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-12">
											<input type="submit" value="Registrar" class="btn btn-primary pull-right push-bottom" data-loading-text="Loading...">
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>

	</div>

</div>
<script>
</script>



















