<?php 
use Admin\Entity\User;
/**
 * @var User $user
 */
$user = $this->user;
$return = $this->url('admin/defaults',array('controller'=>'users'));
?>
<div id="ribbon">
    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
        </span>
    </span>
    <ol class="breadcrumb">
        <li>
            <a href="/admin">
                <i class="fa fa-dashboard"></i>&nbsp;Dashboard
            </a>
        </li>
        <li>Usuários</li>
    </ol>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
        	<br />
        	<div class="box box-primary">
        		<div class="box-body">
                    <div class="box-header with-border">
                    	<h3 class="box-title"><i class="fa fa-eye"></i> Visualizar Dados</h3>
                    </div>
                    <div class="row">
                    	<div class="col-md-12">
                    		<table class="table">
                    			<thead>
                    				<tr>
                    					<th>
                    						Nome
                    					</th>
                    					<th>
                    						Email
                    					</th>
                    					<th>
                    						Membro Desde
                    					</th>
                    					<th>
                    						Ativo
                    					</th>                					
                					</tr>
                    			</thead>
                    			<tbody>
                        			<tr>
                        				<td>
                        					<?=$user->getNome();?>
                        				</td>
                        				<td>
                        					<?=$user->getEmail();?>
                        				</td>
                        				<?php 
                        				$memberAt = $user->getCreatedAt()->format("d/m/Y");
                        				?>
                        				<td>
                        					<?=$memberAt?>
                        				</td>
                        				<?php 
                        				    
                        				if($user->getActive()){
                        				    $ativo = "Ativo";
                        				}else{
                        				    $ativo = "Inativo";
                        				}
                        				    
                        				?>
                        				<td>
                        					<?=$ativo?>
                        				</td>
                    				</tr>                				
                    			</tbody>
                    		</table>
                    		<table class="table">
                    			<thead>
                    				<tr>
                    					<th>
                    						Endereço
                    					</th>
                    					<th>
                    						Número
                    					</th>
                    					<th>
                    						Bairro
                    					</th>
                    					<th>
                    						CEP
                    					</th> 
                    					<th>
                    						Cidade / Estado
                    					</th> 
                    					<th>
                    						RG
                    					</th>               					
                					</tr>
                    			</thead>
                    			<tbody>
                        			<tr>
                        				<td>
                        					<?=$user->getEndereco();?>
                        				</td>
                        				<td>
                        					<?=$user->getNumero();?>
                        				</td>
                        				<td>
                        					<?=$user->getBairro();?>
                        				</td>
                        				<td>
                        					<?=$user->getCep();?>
                        				</td>                    				
                        				<td>
                        					<?=$user->getCity();?> - <?=$user->getState();?>
                        				</td>  
                        				<td>
                        					<?=$user->getRg();?>
                        				</td>               				
                    				</tr>                				
                    			</tbody>                			
                    		</table>
                    	</div>
                    </div>
                </div>
                <div class="box-footer">                  	
                    <a class="btn btn-app"  href="<?=$return?>">
                    	<i class="fa fa-arrow-circle-o-left"></i> Retornar
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>