<?php 
use Admin\Entity\Perfil;
$return = $this->url('admin/defaults',array('controller'=>'perfil'));
/**
 * @var Perfil $perfil
 */
$perfil = $this->entity;
$privileges = json_decode($perfil->getInformation(),true);
$cursos = $privileges['recursos']['cursos'];
$modulos = $privileges['recursos']['modulos'];
$labels = $privileges['recursos']['label'];
?>
<div id="ribbon">
    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
        </span>
    </span>
    <ol class="breadcrumb">
        <li>
            <a href="/admin">
                <i class="fa fa-dashboard"></i>&nbsp;Dashboard
            </a>
        </li>
        <li>Permissões</li>
    </ol>
</div>
<div class="col-md-12 flashMessages">
    <?php
    $flash  =  $this->flashMessenger ();
    echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' ));
    echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' ));
    echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' ));
    echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));

    ?>
</div>
<div id="content">
    <div class="row">
        <form role="form" method="POST" action="">
            <article class="col-sm-12">
                <div class="jarviswidget" id="wid-id-1"
                     data-widget-togglebutton="false"
                     data-widget-editbutton="false"
                     data-widget-fullscreenbutton="false"
                     data-widget-colorbutton="false"
                     data-widget-deletebutton="false">
                    <header>
                        <span class="widget-icon">
                            <i class="fa fa-user-plus txt-color-darken"></i>
                        </span>
                        <h2>Permissões</h2>
                    </header>
                    <div class="padding-15">
                        <div class="widget-body padding-top-10 padding-bottom-10">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Perfil</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><?=$perfil->getNome()?></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>
                                                Recurso
                                            </th>
                                            <th>
                                                Privilégios
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach($modulos as $k=>$modulo){
                                            ?>
                                            <tr>
                                                <td>
                                                    <?=$labels[$k]?>
                                                </td>
                                                <td>
                                                    <div class="form-group">
                                                        <?php
                                                        $action = 'list';
                                                        if(isset($modulo[$action])){?>
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input <?=($modulo[$action])?'checked':''?> name="privilege[<?=$k?>][<?=$action?>]" type="checkbox" value="1">
                                                                    Listar
                                                                </label>
                                                            </div>
                                                            <?php
                                                        }

                                                        $action = 'listAll';
                                                        if(isset($modulo[$action])){?>
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input <?=($modulo[$action])?'checked':''?> name="privilege[<?=$k?>][<?=$action?>]" type="checkbox" value="1">
                                                                    Listar Todos
                                                                </label>
                                                            </div>
                                                            <?php
                                                        }

                                                        $action = 'delete';
                                                        if(isset($modulo[$action])){?>
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input <?=($modulo[$action])?'checked':''?> name="privilege[<?=$k?>][<?=$action?>]" type="checkbox" value="1">
                                                                    Deletar
                                                                </label>
                                                            </div>
                                                            <?php
                                                        }

                                                        $action = 'new';
                                                        if(isset($modulo[$action])){?>
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input <?=($modulo[$action])?'checked':''?> name="privilege[<?=$k?>][<?=$action?>]" type="checkbox" value="1">
                                                                    Criar
                                                                </label>
                                                            </div>
                                                            <?php
                                                        }

                                                        $action = 'edit';
                                                        if(isset($modulo[$action])){?>
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input <?=($modulo[$action])?'checked':''?> name="privilege[<?=$k?>][<?=$action?>]" type="checkbox" value="1">
                                                                    Editar
                                                                </label>
                                                            </div>
                                                            <?php
                                                        }?>
                                                    </div>
                                                </td>
                                            </tr>
                                            <?php
                                        }?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                        <div class="widget-footer padding-top-10 padding-bottom-10">
                            <button type="submit" name="submit" class="btn btn-success" >
                                <i class="fa fa-save"></i> Salvar
                            </button>
                            <button type="reset" name="submit" class="btn btn-info" >
                                <i class="fa fa-eraser"></i> Limpar
                            </button>
                            <a class="btn btn-danger"  href="<?=$return?>">
                                <i class="fa fa-arrow-circle-o-left"></i> Retornar
                            </a>
                        </div>
                    </div>
                </div>
            </article>
        </form>
    </div>
</div>
