<?php
use Doctrine\ORM\EntityManager;

/**
 * @var EntityManager
 * @var \Admin\Entity\User $user
 */

$em     = $this->em;
$user   = $this->userIdentity();
if($user == false){
    header('Location: /auth');
    die;
}

$id_widget = 0;
?>
<div id="ribbon">
        <span class="ribbon-button-alignment">
            <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
                <i class="fa fa-refresh"></i>
            </span>
        </span>
    <ol class="breadcrumb">
        <li>Home</li><li>Dashboard</li>
    </ol>
</div>
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa-fw fa fa-home"></i>
                Dashboard <span>&gt; Meu Dashboard</span>
            </h1>
        </div>
    </div>
    <section id="widget-grid" class="">
        <div class="row">
            <?=$this->partial('partials/acesso-rapido',array('widgetid' => $id_widget++));?>
            <?=$this->partial('partials/atualizar-informacoes',array('widgetid' => $id_widget++,'user' => $user,'em' => $em));?>
        </div>
        <div class="row">
            <?//=$this->partial('partials/graph-myfx',array('widgetid' => $id_widget++));?>
        </div>
    </section>
</div>
