<article class="col-sm-12">
    <div class="jarviswidget" id="wid-id-<?=$this->widgetid?>"
         data-widget-togglebutton="false"
         data-widget-editbutton="false"
         data-widget-fullscreenbutton="false"
         data-widget-colorbutton="false"
         data-widget-deletebutton="false">
        <header>
            <span class="widget-icon">
                <i class="fa fa-fighter-jet txt-color-darken"></i>
            </span>
            <h2>Acesso Rápido</h2>
        </header>
        <div class="padding-15">
            <div class="widget-body padding-top-10">
                <div class="col-sm-3 margin-bottom-10">
                    <div style="position: relative" class="well well-sm bg-color-darken txt-color-white text-center">
                        <p>Meu Cadastro</p>
                        <a href="<?=$this->url('admin/defaults',array('controller' => 'users','action' => 'edit', 'id' => $this->UserIdentity()->getId()))?>" class="btn btn-primary form-control">
                            Acessar <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
                    <br />
                </div>
                <div class="col-sm-3 margin-bottom-10">
                    <div style="position: relative" class="well well-sm bg-color-darken txt-color-white text-center">
                        <p>Contratar Trader Copy</p>
                        <a href="<?=$this->url('panel-ea',array('controller' => 'Index','action' => 'panel-ea', 'id' => $this->UserIdentity()->getId()))?>" class="btn btn-primary form-control">
                            Acessar <i class="fa fa-arrow-circle-right"></i>
                        </a>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>
</article>
